### ISSUE TITLE
manage.py runserver 启动报错

### ISSUE THREAD

**Issue by xkungfu** [charlesXu86/Chatbot_Utils#2]
ubuntu18.04
python3.6.9
tensorflow==2.3.1
(rasa2.0.0rc3)

pip3 install Django
pip3 install django_crontab
pip3 install django-cors-headers
pip3 install requests
pip3 install chatbot_help
pip3 install tensorflow
pip3 install time_convert

python3 manage.py runserver 127.0.0.1:5555 启动报错：
```

Performing system checks...

2020-10-03 20:46:33.746963: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-10-03 20:46:33.747002: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[INFO] Model folder /pyroot/rasa_utils/Base_model/cluener/ner_bert_base/ AttributeError("'NoneType' object has no attribute 'model_checkpoint_path'",)
[INFO] Model folder /pyroot/rasa_utils/Base_model/cluener/ner_bert_base/ AttributeError("'NoneType' object has no attribute 'model_checkpoint_path'",)
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/pyroot/rasa_utils/Chatbot_Utils/urls.py", line 22, in <module>
    path('model/', include("Base_model_rest.urls")),
  File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/pyroot/rasa_utils/Base_model_rest/urls.py", line 20, in <module>
    from Base_model_rest.Api.ner.NER_server import ner_server
  File "/pyroot/rasa_utils/Base_model_rest/Api/ner/NER_server.py", line 21, in <module>
    from Base_model_rest.Api.ner.get_ner_result import get_ner
  File "/pyroot/rasa_utils/Base_model_rest/Api/ner/get_ner_result.py", line 19, in <module>
    ner = NER_model()
  File "/pyroot/rasa_utils/Base_model/cluener/predict_sequence_label.py", line 27, in __init__
    self.sess = self.load_model(self.model_path)
  File "/pyroot/rasa_utils/Base_model/cluener/predict_sequence_label.py", line 86, in load_model
    saver = tf.train.import_meta_graph(input_checkpoint + '.meta', clear_devices=clear_devices)
  File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1462, in import_meta_graph
    **kwargs)[0]
  File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1472, in _import_meta_graph_with_return_elements
    raise RuntimeError("Exporting/importing meta graphs is not supported when "
RuntimeError: Exporting/importing meta graphs is not supported when eager execution is enabled. No graph exists when eager execution is enabled.

```

**Comment by charlesXu86** [comment]
> ubuntu18.04
> python3.6.9
> tensorflow==2.3.1
> (rasa2.0.0rc3)
> 
> pip3 install Django
> pip3 install django_crontab
> pip3 install django-cors-headers
> pip3 install requests
> pip3 install chatbot_help
> pip3 install tensorflow
> pip3 install time_convert
> 
> python3 manage.py runserver 127.0.0.1:5555 启动报错：
> 
> ```
> 
> Performing system checks...
> 
> 2020-10-03 20:46:33.746963: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
> 2020-10-03 20:46:33.747002: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> [INFO] Model folder /pyroot/rasa_utils/Base_model/cluener/ner_bert_base/ AttributeError("'NoneType' object has no attribute 'model_checkpoint_path'",)
> [INFO] Model folder /pyroot/rasa_utils/Base_model/cluener/ner_bert_base/ AttributeError("'NoneType' object has no attribute 'model_checkpoint_path'",)
> Exception in thread django-main-thread:
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.6/threading.py", line 864, in run
>     self._target(*self._args, **self._kwargs)
>   File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
>     fn(*args, **kwargs)
>   File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
>     self.check(display_num_errors=True)
>   File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
>     databases=databases,
>   File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
>     new_errors = check(app_configs=app_configs, databases=databases)
>   File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
>     return check_resolver(resolver)
>   File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
>     return check_method()
>   File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 408, in check
>     for pattern in self.url_patterns:
>   File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
>     res = instance.__dict__[self.name] = self.func(instance)
>   File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
>     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
>   File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
>     res = instance.__dict__[self.name] = self.func(instance)
>   File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
>     return import_module(self.urlconf_name)
>   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/pyroot/rasa_utils/Chatbot_Utils/urls.py", line 22, in <module>
>     path('model/', include("Base_model_rest.urls")),
>   File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
>     urlconf_module = import_module(urlconf_module)
>   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/pyroot/rasa_utils/Base_model_rest/urls.py", line 20, in <module>
>     from Base_model_rest.Api.ner.NER_server import ner_server
>   File "/pyroot/rasa_utils/Base_model_rest/Api/ner/NER_server.py", line 21, in <module>
>     from Base_model_rest.Api.ner.get_ner_result import get_ner
>   File "/pyroot/rasa_utils/Base_model_rest/Api/ner/get_ner_result.py", line 19, in <module>
>     ner = NER_model()
>   File "/pyroot/rasa_utils/Base_model/cluener/predict_sequence_label.py", line 27, in __init__
>     self.sess = self.load_model(self.model_path)
>   File "/pyroot/rasa_utils/Base_model/cluener/predict_sequence_label.py", line 86, in load_model
>     saver = tf.train.import_meta_graph(input_checkpoint + '.meta', clear_devices=clear_devices)
>   File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1462, in import_meta_graph
>     **kwargs)[0]
>   File "/pyroot/rasa_utils/env/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1472, in _import_meta_graph_with_return_elements
>     raise RuntimeError("Exporting/importing meta graphs is not supported when "
> RuntimeError: Exporting/importing meta graphs is not supported when eager execution is enabled. No graph exists when eager execution is enabled.
> ```

你的tf版本问题，用tf1.14
